### ISSUE TITLE
Some improvements to Environment component

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#126]
1. the canvas dimensions should be mapped to the environment width and height (see [here](https://github.com/freedomotic/fd-polymer-environments/blob/3098f769ee05829a07810c48a873f65f93dae65e/fd-polymer-environment.html#L163))
2. background image should be retrieved via API (passing "environment.backgroundImage" to [getResource action](https://github.com/freedomotic/fd-vue-webapp/blob/71319019631e263c2b9932ee6a76b695ea3b8477/src/store/actions.js#L193) - **This requires to fix #113**  
3. the environment name should be placed as in the following image 
![schermata del 2018-07-24 17-17-27](https://user-images.githubusercontent.com/4079634/43148412-7ba50c76-8f65-11e8-8603-e0407c7aa39b.png)

**Comment by amenak77** [comment]
![test_newclient3](https://user-images.githubusercontent.com/13914556/43365151-8438ab24-9328-11e8-80cc-833ead694d70.jpg)
We should also add field "description" and maybe "protocol" between fields "name" and "object type" in webapp "things" label to improve GUI's user friendlyness in order to have thing's: name -> description -> protocol -> type of thing

**Comment by mcicolella** [comment]
I think this type of label should be too long to reproduce on the panel.

**Comment by mcicolella** [comment]
#145 #144 #142
