### ISSUE TITLE
Update README.md with more info about the app

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#3]

**Comment by jtkaufman737** [comment]
Hi, where are you all hosted? I'll help out with this one :)

**Comment by P3trur0** [comment]
HI @jtkaufman737 we're interested in develop a front end client for [Freedomotic](https://github.com/freedomotic/freedomotic) using **Vue.js**.

The idea behind this issue is to start to make the repository description clearer.
So far, this repository is almost empty since we've just prepared a basic scaffolding for a Vue application.

Any help is appreciated!
