### ISSUE TITLE
System component

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#38]
Currently Polymer client shows only a button to shutdown the system.
We should define which controls to add to this component.

![system](https://user-images.githubusercontent.com/4079634/34119091-360d7cf6-e421-11e7-9836-52f59c9c4124.png)

![system2](https://user-images.githubusercontent.com/4079634/34119092-3646e964-e421-11e7-90fe-8c0268ea0d2d.png)

**Comment by P3trur0** [comment]
@mcicolella I am starting to work on this.

**Comment by P3trur0** [comment]
Since we need to communicate events across different components, my idea here is to introduce Vuex and use it also as event bus. See [here](https://vuex.vuejs.org/en/actions.html) for further info.

So, the implementation that I am going to do in order to assess this issue will, somehow, satisfy the requirement defined in #37.

**Comment by mcicolella** [comment]
In this component we could add another option to select the language to use.

**Comment by mcicolella** [comment]
@P3trur0 maybe yes for now even if I'd like to enable these commands only for administrators or users with high privileges.

**Comment by P3trur0** [comment]
I close this issue. Please refer to #118 for further enhancements.
